#!/bin/bash
# Just keep xdg-dektop-portal & xdg-desktop-portal hyprland packages and remove all others
#sleep 1
# killall xdg-desktop-portal-hyprland
# killall xdg-desktop-portal-wlr
# killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
#sleep 2
#/usr/lib/xdg-desktop-portal &
#pkexec /usr/local/bin/swhks &
