-- Hyprland 0.53 Configuration
-- Author: Thaer Maddah
-- Date: 30-12-2025

-- █▀▀ ▀▄▀ █▀▀ █▀▀
-- ██▄ █░█ ██▄ █▄▄

-- These configuration for Emacs and other programs run correctly on XWayland  
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("DISPLAY", ":0")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
-- TODO: manual review — malformed env on line 13: GDK_BACKEND,wayland,x11
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

--exec-once = $HOME/.config/hypr/autostart
-- exec-once=/usr/lib/polkit-kde-authentication-agent-1
-- exec-once = echo us > /tmp/kb_layout
--exec-once = wlsunset -S 9:00 -s 19:30 	# set sunrise option
--exec-once = hypridle

-- Run Notification Center on waybar 
-- exec-once = hyprctl notify -1 5000 "rgb(ff1ea3)" "Welcome to Hyprland!"

-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

-- █ █▄░█ █▀█ █░█ ▀█▀
-- █ █░▀█ █▀▀ █▄█ ░█░

hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2,
    bezier = "overshot",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2,
    bezier = "smoothOut",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 2,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 2,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 2,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2,
    bezier = "default",
})

hl.bind("Print", hl.dsp.exec_cmd("~/git/dotfiles/scripts/capture.sh full"))

hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -a -n"))
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("CTRL + SUPER + S", hl.dsp.exec_cmd("systemctl suspend"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("foot"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("killall wofi || wofi --show drun"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("killall rofi || rofi -theme sidebar -show drun"))
hl.bind("SUPER + period", hl.dsp.exec_cmd("killall rofi || rofi -show emoji -emoji-format \"{emoji}\" -modi emoji -theme ~/.config/rofi/global/emoji"))
hl.bind("SUPER + escape", hl.dsp.exec_cmd("wlogout --protocol layer-shell -b 3"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd("~/git/dotfiles/scripts/capture.sh"))

hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + SHIFT + Q", hl.dsp.exit())
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind("SUPER + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + P", hl.dsp.window.pseudo())

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

hl.bind("SUPER + CTRL + h", hl.dsp.window.resize({ x = -20, y = 0, relative = true }))
hl.bind("SUPER + CTRL + l", hl.dsp.window.resize({ x = 20, y = 0, relative = true }))
hl.bind("SUPER + CTRL + j", hl.dsp.window.resize({ x = 0, y = -20, relative = true }))
hl.bind("SUPER + CTRL + k", hl.dsp.window.resize({ x = 0, y = 20, relative = true }))

hl.bind("SUPER + t", hl.dsp.group.toggle())
-- TODO: manual review on line 263 — changegroupactive: expected 'f', 'b', or an index (got "")
-- hl.bind("SUPER + tab", hl.dsp.changegroupactive())

hl.bind("SUPER + c", hl.dsp.workspace.toggle_special(""))
-- hl.bind("SUPERSHIFT + c", hl.dsp.window.move({ workspace = "special" }))

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("CTRL + ALT + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("CTRL + ALT + left", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER + Home", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +10%"))
hl.bind("SUPER + End", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -10%"))
hl.bind("SUPER + Delete", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))

hl.bind("SUPER + Prior", hl.dsp.exec_cmd("brightnessctl  set +10"))
hl.bind("SUPER + Next", hl.dsp.exec_cmd("brightnessctl  set 10-"))

hl.config({
    input = {
        kb_layout = "us, ara",
        kb_options = "grp:alt_caps_toggle",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        numlock_by_default = true,
    },
    -- █▀▀ █▀▀ █▄░█ █▀▀ █▀█ ▄▀█ █░░
    -- █▄█ ██▄ █░▀█ ██▄ █▀▄ █▀█ █▄▄
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 2,
        -- diable feaeture for hyprland 0.53
        -- no_border_on_floating = false
        col = {
            active_border = 0xffe66e1e,
        },
        --col.group_border_active=0xffe66e1e
        layout = "master",
        --layout = dwindle
    },
    -- █▀▄▀█ █ █▀ █▀▀
    -- █░▀░█ █ ▄█ █▄▄
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        --vfr = true
        enable_swallow = true,
        swallow_regex = "^(foot)$",
    },
    -- █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
    -- █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█
    decoration = {
        -- █▀█ █▀█ █░█ █▄░█ █▀▄   █▀▀ █▀█ █▀█ █▄░█ █▀▀ █▀█
        -- █▀▄ █▄█ █▄█ █░▀█ █▄▀   █▄▄ █▄█ █▀▄ █░▀█ ██▄ █▀▄
        rounding = 5,
        -- █▀█ █▀█ ▄▀█ █▀▀ █ ▀█▀ █▄█
        -- █▄█ █▀▀ █▀█ █▄▄ █ ░█░ ░█░
        active_opacity = 0.9,
        inactive_opacity = 0.9,
        -- disable feature for hyprland 0.53
        -- windowrulev2 = opacity 0.95 0.95,class:^(thunar)$
        -- █▄▄ █░░ █░█ █▀█
        -- █▄█ █▄▄ █▄█ █▀▄
        --blur = true
        --blur_size = 3
        --blur_passes = 3
        --blur_new_optimizations = true
        -- █▀ █░█ ▄▀█ █▀▄ █▀█ █░█░█
        -- ▄█ █▀█ █▀█ █▄▀ █▄█ ▀▄▀▄▀
        -- drop_shadow = true
        --shadow_ignore_window = true
        --shadow_offset = 2 2
        --shadow_range = 4
        --shadow_render_power = 2
        --col.shadow = 0x66000000
        --blurls = gtk-layer-shell
        -- blurls = waybar
        --blurls = lockscreen
    },
    -- ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
    -- █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
    animations = {
        enabled = true,
        -- █▄▄ █▀▀ ▀█ █ █▀▀ █▀█   █▀▀ █░█ █▀█ █░█ █▀▀
        -- █▄█ ██▄ █▄ █ ██▄ █▀▄   █▄▄ █▄█ █▀▄ ▀▄▀ ██▄
    },
    -- █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
    -- █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█
    -- dwindle {
    --     #no_gaps_when_only = false
    --     pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    --     preserve_split = true # you probably want this
    --     force_split=2     # 0 -> split follows mouse, 1 -> always split to the left (new = left or top) 2 -> always split to the right (new = right or bottom)
    -- }
    master = {
        --no_gaps_when_only= false
        --new_is_master=false    # whether a newly open window should replace the master or join the slaves.
        orientation = "left",
    },
    -- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
    -- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█
    --windowrule = float, file_progress
    --windowrule = float, confirm
    --windowrule = float, size 800 600, dialog
    --windowrule = float, download
    --windowrule = float, notification
    --windowrule = float, error
    --windowrule = float, splash
    --windowrule = float, confirmreset
    --windowrule = float, title:Open File
    --windowrule = float, title:branchdialog
    --windowrule = float, Lxappearance
    --windowrule = float, Rofi
    --windowrule = animation none,Rofi
    --windowrule = float, viewnior
    --windowrule = float, Viewnior
    --windowrule = float, feh
    --windowrule = float, pavucontrol-qt
    --windowrule = float, pavucontrol
    --windowrule = float, file-roller
    --windowrule = fullscreen, wlogout
    --windowrule = float, title:wlogout
    --windowrule = fullscreen, title:wlogout
    --windowrule = idleinhibit focus, mpv
    --windowrule = idleinhibit fullscreen, firefox
    --windowrule = float, title:^(Media viewer)$
    --windowrule = float, title:^(Volume Control)$
    --windowrule = float, title:^(Picture-in-Picture)$
    -- windowrule = float, size 800 600,class:^(libreoffice-writer)$,title:^(Open)$
    --windowrule=float,^(gnome-system-monitor)$
    --windowrule=float, plasma-systemmonitor
    -- disable feature for hyprland 0.53
    -- windowrule = size 800 600, title:^(Volume Control)$
    -- windowrule = move 75 44%, title:^(Volume Control)$
    -- █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
    -- █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀
    -- █▀ █▀▀ █▀█ █▀▀ █▀▀ █▄░█ █▀ █░█ █▀█ ▀█▀
    -- ▄█ █▄▄ █▀▄ ██▄ ██▄ █░▀█ ▄█ █▀█ █▄█ ░█░
    --bind = SUPERSHIFT, S, exec, ~/.scripts/screensht area
    -- bind = SUPER, Print, exec, grim -g "$(slurp)" $HOME/Pictures/Screenshots/screenshot-$(date +%Y%m%d_%H%M%S).png
    -- █▀▄▀█ █ █▀ █▀▀
    -- █░▀░█ █ ▄█ █▄▄
    -- Print screen
    -- bind = SUPER, Print, exec, gnome-screenshot -i
    -- bind = SUPER_L SHIFT_L, F23, exec, gnome-system-monitor
    -- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
    -- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░
    -- bind = SUPER, S, togglesplit, # dwindle
    -- █▀▀ █▀█ █▀▀ █░█ █▀
    -- █▀░ █▄█ █▄▄ █▄█ ▄█
    --Vim bindings
    -- █▀▄▀█ █▀█ █░█ █▀▀
    -- █░▀░█ █▄█ ▀▄▀ ██▄
    --Vim bindings
    -- █▀█ █▀▀ █▀ █ ▀█ █▀▀
    -- █▀▄ ██▄ ▄█ █ █▄ ██▄
    -- ▀█▀ ▄▀█ █▄▄ █▄▄ █▀▀ █▀▄
    -- ░█░ █▀█ █▄█ █▄█ ██▄ █▄▀
    -- █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
    -- ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄
    -- █▀ █░█░█ █ ▀█▀ █▀▀ █░█
    -- ▄█ ▀▄▀▄▀ █ ░█░ █▄▄ █▀█
    -- █▀▄▀█ █▀█ █░█ █▀▀
    -- █░▀░█ █▄█ ▀▄▀ ██▄
    -- █▀▄▀█ █▀█ █░█ █▀ █▀▀   █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀
    -- █░▀░█ █▄█ █▄█ ▄█ ██▄   █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█
    -- my binding kyes 
    -- Screen 
})

hl.on("hyprland.start", function()
    hl.exec_cmd("wl-clipboard-history -t")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("swaybg -m fill -i ~/Pictures/wallpapers/pexels-eberhardgross-1612351.jpg &")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("sleep 3 && notify-send -t 5000 \"welcome $USER to $XDG_CURRENT_DESKTOP\"")
    hl.exec_cmd("sleep 5 && swaync-client -C")
end)

