#!/bin/ksh

_RED="\[\033[1;31m\]"
_GREEN="\[\033[1;32m\]"
_YELLOW="\[\033[1;33m\]"
_BLUE="\[\033[1;34m\]"
_MAGENTA="\[\033[1;35m\]"
_CYAN="\[\033[1;36m\]"
_WHITE="\[\033[1;37m\]"
_RESET="\[\033[0;0m\]"  # reset color to default color


GIT=$HOME/git
DOTFILES=$GIT/dotfiles
CODEDIR=$GIT/Code
export XDG_CONFIG_HOME=~/.config

[[ -f ~/.profile ]] && . "$HOME"/.profile

[[ -f "$DOTFILES"/bash/aliases ]] && . "$DOTFILES"/bash/aliases

# PS1='$LOGNAME-> '


