#!/bin/ksh

_RED="^[[1;31m"
_GREEN='\033[1;32m'
_YELLOW="\[\033[1;33m\]"
_BLUE="\033[1;34m"
_MAGENTA="\[\033[1;35m\]"
_CYAN="\[\033[1;36m\]"
_WHITE="\[\033[1;37m\]"
_RESET="\033[0m"  # reset color to default color
#print "${_GREEN}Hello "

GIT=$HOME/git
DOTFILES=$GIT/dotfiles
CODEDIR=$GIT/Code
export XDG_CONFIG_HOME=~/.config

[[ -f ~/.profile ]] && . "$HOME"/.profile

[[ -f "$DOTFILES"/bash/aliases ]] && . "$DOTFILES"/bash/aliases

# PS1='$LOGNAME-> '
PS1='$(print "$_GREEN")|-${PWD}$(print "\n|-> $_RESET")'

#PS1=$'\a\e[36m\a${USER:=$(ulimit -c 0; id -un 2>/dev/null || echo
#\?)}@${HOSTNAME%%.*}\a\e[34m\a\e[0;33m\a$(local d=${PWD:-?} p=~; [[ $p = ?(*/) ]] || d=${d/#$p/~};
#print -nr -- "$d")\a\e[1;34m\a |\n ^ ^  ^ ^ | \a\e[32m\a$(date +%H:%M)\a\e[34m\a |'
export PS1

# HISTFILE="$HOME/.ksh_history"
# HISTSIZE=5000

# HISTFILE=~/.ksh_hist/ksh_hist.$(tty | sed 's;.*/;;')
# HISTSIZE=10000

# export VISUAL="emacs"
# export EDITOR="$VISUAL"
set -o emacs

# bind ^L=clear-screen
