#!/bin/bash
#
#Environment Variables
export EDITOR=nvim
feh --bg-fill --randomize ~/Pictures/wallpapers/*  

# set the keyboard keystroks speed
xset r rate 300 50

# [[ -z "$TMUX" ]] && exec tmux
[[ -f /usr/bin/numlockx ]] && numlockx
# [[ "$((tty))" = "/dev/tty1" ]]; startx ~/.config/X11/qtie/xinitrc 
# [[ "$((tty))" = "/dev/tty2" ]]; startx  ~/.config/X11/xmonad/xinitrc

# create history file for every tty
if [[ $SHELL == "/bin/ksh" || $SHELL == "/bin/mksh" ]]; then
    HISTFILE=~/.ksh_hist/ksh_hist.$(tty | sed 's;.*/;;')
    HISTSIZE=10000
fi

# if [[ $XDG_CURRENT_DESKTOP == "Hyprland"  ]]; then
# killall xdg-desktop-portal-gnome
# killall xdg-desktop-portal
# killall xdg-desktop-portal-gtk
# # /usr/lib/xdg-desktop-portal-hyprland &
# fi

#Xsecurelock variables --------{{{
# Xsecurelock Variables
export XSECURELOCK_PASSWORD_PROMPT=asterisks
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_LIST_VIDEOS_COMMAND='find "$HOME"/Pictures/wallpapers/ -type f'
export XSECURELOCK_IMAGE_DURATION_SECONDS=10
#export XSECURELOCK_SHOW_DATETIME=1
 
#}}}
