#!/bin/bash
#
#Environment Variables
export EDITOR=nvim
feh --bg-fill --randomize ~/Pictures/wallpapers/* & > /dev/null 2>&1
# [[ -z "$TMUX" ]] && exec tmux
[[ -f /usr/bin/numlockx ]] && numlockx
# [[ "$((tty))" = "/dev/tty1" ]]; startx ~/.config/X11/qtie/xinitrc 
# [[ "$((tty))" = "/dev/tty2" ]]; startx  ~/.config/X11/xmonad/xinitrc

#Xsecurelock variables --------{{{
# Xsecurelock Variables
export XSECURELOCK_PASSWORD_PROMPT=asterisks
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_LIST_VIDEOS_COMMAND='find "$HOME"/Pictures/wallpapers/ -type f'
export XSECURELOCK_IMAGE_DURATION_SECONDS=10
#export XSECURELOCK_SHOW_DATETIME=1
 
#}}}
